
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Navigation"; //// using a reusable component in the page
import FinanceContextprovider from "@/lib/store/financeContext"
import AuthContextProvider from "@/lib/store/authContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <FinanceContextprovider>
            <Nav />
            {children}
          </FinanceContextprovider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
